apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: mongo
spec:
  serviceName: "mongo"
  replicas: 1
  selector:
    matchLabels:
      name: mongo
  template:
    metadata:
      labels:
        name: mongo
        selector: mongo
    spec:
      volumes:
        - name: pv-volume
          persistentVolumeClaim:
            claimName: pv-claim
      containers:
        - name: mongo
          image: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: test
          command:
            - mongod
            - "--bind_ip"
            - 0.0.0.0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: pv-volume
              mountPath: /mnt/data
